baseURL = 'https://supercollider-2025.github.io/'
languageCode = 'en-us'
title = 'The Future of SuperCollider'
theme = 'ananke'
publishDir = "docs"

[params]
site_logo = 'img/sc_cube_48x48_25.png'
    [params.ananke]
        show_recent_posts = false

[menu]
[[menu.main]]
  name = 'Keynote Speakers'
  weight = 1
  url = '/keynote-speakers/'
[[menu.main]]
  name = 'Schedule'
  weight = 2
  url = '/schedule/'
[[menu.main]]
  name = 'Location'
  weight = 3
  url = '/location/'
[[menu.main]]
  name = 'Registration'
  weight = 4
  url = '/registration/'
[[menu.main]]
  name = 'Resources'
  weight = 5
  url = '/resources/'
[[menu.main]]
  name = 'Streaming'
  weight = 6
  url = '/streaming/'